Search profiles (admin/component)
KraosFex/PROYECTO_PF pull request #62
Opened 2022-06-18 15:50 UTC by mihue14

2022-06-18 21:15 UTC, ChampiMagic requested changes
![Captura de pantalla 2022-06-18 180516](https://user-images.githubusercontent.com/97173716/174457058-6c5ddf3e-4f83-473a-af1c-57305f7ca775.jpg)

En esta action deberías cambiar el POST por un GET. 

Luego, el Token se lo deberías pasar así:
![Captura de pantalla 2022-06-18 180810](https://user-images.githubusercontent.com/97173716/174457113-ab9ad6e5-5785-469b-829f-ad021ed93ec3.jpg)
Y lo único que le parias por body seria el username.

En tu componente el "authorization" deberías sacarlo porque el token ya se lo enviarías en la action y también deberías quitar el el useSelector porque no es necesario tener al objeto user
![Captura de pantalla 2022-06-18 180554](https://user-images.githubusercontent.com/97173716/174457192-29a6fdc5-32c0-4373-bd65-b28c96579b2a.jpg)

2022-06-18 21:32 UTC, KraosFex commented on client-app/redux/actions/index.js
> +console.log("🚀 ~ file: index.js ~ line 117 ~ findByUsername ~ usernameAndToken", usernameAndToken.authorization)
Deberias quitar este console.log. si solo lo tenias de testing

2022-06-19 15:14 UTC, ChampiMagic submitted a review, later dismissed

2022-06-19 15:21 UTC, ChampiMagic approved these changes

2022-06-19 17:02 UTC, KraosFex commented on client-app/redux/actions/index.js
> +      console.log(err);
este console.log deberias pasarlo como como un:
`new Error(err)`

2022-06-19 17:02 UTC, KraosFex commented on client-app/src/components/searchProfiles/searchProfiles.jsx
> +        console.log(input)
solo faltaria que elimines este console.log, que esta de mas

2022-06-19 18:08 UTC, merged